### ISSUE TITLE
not found 'assl' package.

### ISSUE THREAD

**Issue by kimsojeong1225** [Audio-WestlakeU/audiossl#4] opened 2022-07-19 04:51 UTC
Hi, Thanks for the great work!
When I ran audioset.py to convert Audioset to lmdb-format, met "ModuleNotFoundError: No module named 'assl' "
I think 'audiossl' repository hasn't module named 'assl'
How can I solve it?

**Comment by lmaxwell** [comment] 2022-08-09 11:08
Thank you for your interest in our work! I'm sorry for late response.  
'assl' module is deprecated and I forgot to clean the code in audiossl. I am sure assl is only used in dataset preparation.  
Now the main branch has solved the problem.

**Comment by lmaxwell** [comment] 2022-09-02 05:42
Close this issue since there is no update for a long time. Feel free to reopen it if the issue is reproduced or you have anything new for sharing and debugging.

**Closed by lmaxwell** 2022-09-02 05:42 UTC
